train:
  stage: 1
  wandb: recursalai-mi325x-node
  wandb_run_name: hxa07c-qwen3-0.6b-stage1
  max_trained_tokens: 100000000

  teacher_hf: Qwen/Qwen3-0.6B-Base
  output_dir: /home/rwkv/smerky/hfd/output/qwen3-0.6b-base/hxa07c-stage1

  raw_data: ["/home/rwkv/smerky/qrwkv/data/mose/instruct","/home/rwkv/smerky/qrwkv/data/mose/raw"]

  max_seq_length: 512

  gradient_clip_val: 1.0
  grad_cp: 1
  lr_init: 1e-4
  lr_final: 1e-4
  weight_decay: 0.001
  
  micro_bsz: 4
  n_gpu_per_node: 8
  n_nodes: 1

